run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    - govet
    - goimports
    - misspell
    - revive
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
